In [1]:
s="Hi there Sam!"
s=s.split()
print(s)

['Hi', 'there', 'Sam!']


In [16]:
planet="Earth"
diameter=12742
print('The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


In [4]:
d={
    'k1' :[1,2,3,{
        'tricky':['oh','man','inception',{
            'target':[1,2,3,'hello']
        }]
    }]
}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [6]:
import numpy as np
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
import numpy as np
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
import numpy as np
x=np.arange(20,35)
y=(x%2==0)
z=x[y]
print(z)

[20 22 24 26 28 30 32 34]


In [11]:
import numpy as np
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
con=np.concatenate((a,b))
print(con)

[1 2 3 4 5 6]


In [29]:
import pandas as pd 
data ={'Name':['Tom','Ram'],'Age':[21,21],'Dept':['CSE','BME']}
df=pd.DataFrame(data) 
print(df)

  Name  Age Dept
0  Tom   21  CSE
1  Ram   21  BME


In [22]:
import pandas as pd
date1 = pd.date_range(start='1-1-2023',end='2-10-2023')
for val in date1:
    print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


In [25]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame.from_records(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
